Declare @orden_excel int = 31791
Declare @orden_DW int	 =(select [ID_DIMORDENFABRICACION]
							FROM [PLDW].[maestro].[DIMORDENFABRICACION] 
							Where COD_REGION_PAIS=7 and COD_ORDEN_FABRICACION= @orden_excel);



select a.ID_DIMORDENFABRICACION
	   ,b.COD_ARTICULO
	   ,b.DESCRIPCION
	   ,a.CONSUMO_ESTANDAR_CANTIDAD_PEDIDA
	   ,a.CANTIDAD_ACEPTADA
	   ,a.VALOR_CONSUMO_ESTANDAR
	   ,a.VALOR_COSTO_ESTANDAR_DOLARES
FROM operaciones.FACT_CONSUMO_ESTANDAR a
left join [maestro].[DIMARTICULO] b			on b.ID_DIMARTICULO= a.ID_DIMARTICULO
where a.ID_DIMORDENFABRICACION= @orden_DW
order by b.COD_ARTICULO