Declare @orden_excel int = 31791
Declare @orden_DW int	 =(select [ID_DIMORDENFABRICACION]
							FROM [PLDW].[maestro].[DIMORDENFABRICACION] 
							Where COD_REGION_PAIS=7 and COD_ORDEN_FABRICACION= @orden_excel);

select ID_DIMORDENFABRICACION
		,COD_TIPO_BOLETIN
		,DESCRIPCION
		,Consumo
		,[Agrupador Consumo]
		,VALOR_OPERACION_HORAS_ESTANDAR
		,VALOR_COSTO_HORAS_DOLARES_ESTANDAR
		,VALOR_COSTO_HORAS_ESTANDAR
FROM PLDW.dbo.HORAS_ESTANDAR_FACT_V
where ID_DIMORDENFABRICACION= @orden_DW